spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa

token:
  expiration_time: 86400000
  secret: user_token_userservice

gateway:
  ip: 192.168.123.107
order_service:
  url: http://127.0.0.1:8000/order-service/%s/orders