create table if not exists catalog(
 id bigint generated by default as identity,
 create_at timestamp default CURRENT_TIMESTAMP not null,
 product_id varchar(120) not null,
 product_name varchar(255) not null,
 stock integer not null,
 unit_price integer not null,
 primary key (id)
);